Repository 7T4-DevPlus/OJT-Project1, pull requests merged in 2023-11, with the labels that each got.

#4 create session 1 of home page
  home.html
Labels: documentation, enhancement

#5 Create session 2 of body for home page
  home.html
  style.css
Labels: documentation, enhancement

#2 Task ojt7 t4 72/session3
  body.html
  home.html
  style.css
Labels: documentation, enhancement

#7 Body of home page
  body.html
  home.html
  style.css
Labels: documentation, enhancement

#12 Feature ojt7 t4 67/search box
  home.html
  navbar.css
  navbar.html
  search.js
Labels: documentation, enhancement

#13 Create login and register page with validation.
  home.html
  loginsignup.css
  loginsignup.html
  loginsignup.js
Labels: documentation, enhancement

#15 This is footer of website
  footer.css
  footer.html
  home.html
Labels: documentation, enhancement

#17 Footer
  footer.css
  footer.html
Labels: documentation, enhancement

#19 Refactor sprint 1
  css/home.css
  css/navbar.css
  footer.css
  footer.html
  home.html
  js/header_home.js
  js/search.js
  loginsignup.css
  loginsignup.js
  navbar.css
  navbar.html
  navbar.js
  script.js
  search.js
  style.css
Labels: bug, documentation

#20 Feature ojt7 t4 50/product modal
  css/home.css
  footer.html
  home.html
  js/product_modal.js
  navbar.html
Labels: bug, documentation, enhancement

#21 Finish Feature OJT7T4-29 Profile page
  css/userprofile.css
  userprofile.html
Labels: documentation, enhancement

#25 create check out page
  .idea/.gitignore
  .idea/OJT-Project1.iml
  .idea/modules.xml
  .idea/vcs.xml
  checkout.html
  css/checkout.css
  js/checkout.js
Labels: documentation, enhancement

#26 Finish cart page
  cart.html
  css/cart.css
  css/userprofile.css
Labels: documentation, enhancement

#27 Feature ojt7 t4 36/product details
  .DS_Store
  css/ProDetail.css
  js/ProDetail.Js
  productDetail.html
  productDetail.json
Labels: documentation, enhancement

#28 Refactor sprint2
  .DS_Store
  checkout.html
  css/loginsignup.css
  css/navbar.css
  footer.html
  js/database.js
  js/viewproducts.js
  loginsignup.html
  navbar.html
  productDetail.json
Labels: documentation, enhancement

#29 Feature ojt7 t4 32/authentication
  css/home.css
  css/userprofile.css
  css/viewproducts.css
  footer.html
  home.html
  js/loginsignup.js
  js/navbar.js
  js/userProfile.js
  js/viewproducts.js
  loginsignup.html
  navbar.html
  products.html
  userProfile.html
Labels: documentation, enhancement

#30 Add scroll bar to product cart in checkout page
  checkout.html
  css/checkout.css
  js/checkout.js
Labels: documentation

#31 Feature ojt7 t4 45/search by name
  css/navbar.css
  css/viewproducts.css
  home.html
  js/navbar.js
  js/viewproducts.js
  navbar.html
  products.html
Labels: bug, documentation, enhancement

#32 Add sort function with price range product sort
  css/viewproducts.css
  js/viewproducts.js
  products.html
Labels: documentation, enhancement

#36 Feature ojt7 t4 75/link data products
  .DS_Store
  js/ProDetail.Js
  js/viewproducts.js
  productDetail.html
  service/base.js
Labels: documentation, enhancement

#37 finished checkout function
  checkout.html
  js/checkout.js
Labels: documentation, enhancement

#35 This is Feature-OJT7T4-69/mailling(Optional)
  .idea/.gitignore
  .idea/OJT-Project1.iml
  .idea/modules.xml
  .idea/vcs.xml
  checkout.html
  footer.html
Labels: documentation, enhancement
